version: '3'
networks:
  dotbit:
    ipam:
      driver: default
      config:
        - subnet: 182.17.0.0/16
          gateway: 182.17.0.1

services:
  das-database:
    image: dotbitteam/das-database:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/das-database", "--config", "/app/config/config.yaml" ]
    ports:
      - ${DAS_DATABASE_PORT:-8118}:8118
    volumes:
      - $PWD/config/config.database.yaml:/app/config/config.yaml
    depends_on:
      - mysql
    networks:
      - dotbit
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - $PWD/mysql-data:/var/lib/mysql
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DAS_DB_PORT:-123456}
      TZ: Asia/Shanghai
      # This allows ip ranges from 182.17.0.1 to 182.17.255.255 to connect to root
      MYSQL_ROOT_HOST: "182.17.%.%"
    networks:
      - dotbit

  das-register:
    image: dotbitteam/das-register:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/das-register", "--config", "/app/config/config.yaml" ]
    ports:
      - ${DAS_REGISTER_INTERNAL_PORT:-8119}:8119
      - ${DAS_REGISTER_PORT:-8120}:8120
    volumes:
      - $PWD/config/config.yaml:/app/config/config.yaml
    depends_on:
      - das-database
      - redis
    networks:
      - dotbit
    extra_hosts:
      - host.docker.internal:host-gateway

  redis:
    image: redis:5.0
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - dotbit
